### 기사님 회원가입 테스트
POST http://localhost:5050/auth/sign-up
Content-Type: application/json

{
  "name": "SJ",
  "email": "mover100@example.com",
  "phoneNumber": "010-1234-5678",
  "password": "testpassword1!",
  "currentRole": "MOVER"
}

### 기사님 로그인 테스트
POST http://localhost:5050/auth/sign-in
Content-Type: application/json

{
  "email": "mover100@example.com",
  "password": "testpassword1!"
}

### 기사님 기본정보 수정 테스트(1)
PATCH http://localhost:5050/users/profile/mover/basic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJuYW1lIjoiU0oiLCJyb2xlIjoiTU9WRVIiLCJpYXQiOjE3NTI3Mzg3MDUsImV4cCI6MTc1Mzk0ODMwNX0.INUifb5PsVbmB55n7UsJsQurFDhVCMQZMvtaEVzgQxg

{
  "name": "수정이",
  "phoneNumber": "010-1111-2222",
  "currentPassword": "newpassword2!",
  "newPassword": "testpassword1!"
} 

### 기사님 기본정보 수정 테스트(2)
PATCH http://localhost:5050/users/profile/mover/basic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJuYW1lIjoiU0oiLCJyb2xlIjoiTU9WRVIiLCJpYXQiOjE3NTI3Mzg3MDUsImV4cCI6MTc1Mzk0ODMwNX0.INUifb5PsVbmB55n7UsJsQurFDhVCMQZMvtaEVzgQxg

{
  "name": "수정이",
  "phoneNumber": "010-1111-2222",
  "currentPassword": "testpassword1!",
  "newPassword": "newpassword2!"
} 